name: Python CI/CD to Azure Web App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # =========================
  # BUILD STAGE
  # =========================
  build:
    name: Build Python Application
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Run Bash command
        run: |
          echo "Hello from Bash"
          pwd
          ls -la
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10'

  #     - name: Create virtual environment
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate

  #     - name: Install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip install -r requirements.txt

  #     # Package app for deployment
  #     - name: Create deployment package
  #       run: |
  #         zip -r python-app.zip . \
  #           -x "venv/*" ".git/*" ".github/*"

  #     - name: Upload build artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: python-app
  #         path: python-app.zip

  # # =========================
  # # DEPLOY STAGE
  # # =========================
  # deploy:
  #   name: Deploy to Azure Web App
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Download build artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-app

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: hello-python-app-<unique-name>
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: python-app.zip
